services:
  application:
    build: ./publisher
    restart: unless-stopped
    ports:
     - "80:80"
     - "443:443"
    environment:
      APP_ENV: dev
    volumes:
      - ./publisher:/var/www/html
      - vendor:/var/www/html/vendor
  subscriber:
    build: ./subscriber
    restart: unless-stopped
    volumes:
      - ./subscriber:/app
      - /app/node_modules
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_logs:/var/log/rabbitmq
volumes:
  rabbitmq_data:
  rabbitmq_logs:
  vendor:
  node_modules: